name: Docker Image CI

env:
  DOCKER_ID: ${{ secrets.DOCKER_ID }}
  DOCKER_PW: ${{ secrets.DOCKER_PW }}
  IMAGE_NAME: entropy

on:
  workflow_dispatch:
  push:
    tags:
      - v*.*.*

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build & push the docker image
      run: |
        docker build -t $DOCKER_ID/$IMAGE_NAME:$(jq -r .version package.json) -t $DOCKER_ID/$IMAGE_NAME:latest .
        docker login -u $DOCKER_ID -p $DOCKER_PW
        docker push $DOCKER_ID/$IMAGE_NAME:$(jq -r .version package.json)
        docker push $DOCKER_ID/$IMAGE_NAME:latest
